eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka/
    # spring-boot-starter-actuatorÒÀÀµ
    healthcheck:
      enabled: true
  instance:
    # ĞÄÌøÃë
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10

server:
  port: 8763
spring:
  application:
    name: eureka_client