eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka/
    # spring-boot-starter-actuator依赖
    healthcheck:
      enabled: true
  instance:
    # 心跳秒
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10

server:
  port: 8763
spring:
  application:
    name: eureka_client

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@